version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

# This tells GoReleaser to use the Gitea/Forgejo API format
release:
  # It will automatically use the GITEA_TOKEN you passed in the workflow
  # and parse the repository URL from your git remote.